name: (Admin) BTP Download into GIT download Branch

on:
  workflow_dispatch:
    inputs:
      ids:
        description: "Comma-separated list of IDs to be downloaded"
        required: true
        type: string
      source-env:
        description: "Environment - Source BTP for Download"
        required: true
        type: choice
        options:
          - "DEV"
          - "TST"
      mode:
        description: "Mode IntegrationPackages/PartnerDirectory"
        required: true
        type: choice
        options:
          - IntegrationPackages
          - PartnerDirectory
      commit-message:
        description: "JIRA Story / SNOW Incident"
        required: true
        type: string
permissions:
  contents: write

jobs:
  initialize:
    name: Authorize & Read Environment Variables for ${{ inputs.source-env }}
    runs-on: ${{ vars.RUNS_ON && fromJson(vars.RUNS_ON) || 'ubuntu-latest' }}
    environment: ${{ inputs.source-env }}
    outputs:
      btp-api-user: ${{ steps.export.outputs.btp-api-user }}
      btp-tec-user: ${{ steps.export.outputs.btp-tec-user }}
      btp-token-url: ${{ steps.export.outputs.btp-token-url }}
      btp-api-url: ${{ steps.export.outputs.btp-api-url }}
      git-cicd-orgrepo: ${{ steps.export.outputs.git-cicd-orgrepo }}
      git-cicd-ref: ${{ steps.export.outputs.git-cicd-ref }}
      git-target-branch: ${{ steps.export.outputs.git-target-branch }}
    steps:
      - name: Export vars
        id: export
        run: |
          echo "btp-api-user=${{ vars.BTP_API_USER }}" >> $GITHUB_OUTPUT
          echo "btp-tec-user=${{ vars.BTP_TEC_USER }}" >> $GITHUB_OUTPUT
          echo "btp-token-url=${{ vars.BTP_TOKEN_URL }}" >> $GITHUB_OUTPUT
          echo "btp-api-url=${{ vars.BTP_API_URL }}" >> $GITHUB_OUTPUT
          echo "git-cicd-orgrepo=${{ vars.GIT_CICD_ORGREPO }}" >> $GITHUB_OUTPUT
          echo "git-cicd-ref=${{ vars.GIT_CICD_REF }}" >> $GITHUB_OUTPUT
          echo "git-target-branch=${{ vars.GIT_TARGET_BRANCH || 'main' }}" >> $GITHUB_OUTPUT

  btp-download-package:
    needs: [initialize]
    name: Download from BTP to GIT
    uses: SAP/cicd-actions-for-sap-integration-suite/.github/workflows/download-btp-to-git.yml@v1.3.0
    with:
       workflow-ref: ${{ needs.initialize.outputs.git-cicd-ref }}
       source-env: ${{ inputs.source-env }}
       target-ref: ${{ needs.initialize.outputs.git-target-branch }}
       ids: ${{ inputs.ids }}
       mode: ${{ inputs.mode }}
       commit-message: ${{ inputs.commit-message }}
       btp-api-user: ${{ needs.initialize.outputs.btp-api-user }}
       btp-tec-user: ${{ needs.initialize.outputs.btp-tec-user }}
       btp-token-url: ${{ needs.initialize.outputs.btp-token-url }}
       btp-api-url: ${{ needs.initialize.outputs.btp-api-url }}
       git-cicd-orgrepo: ${{ needs.initialize.outputs.git-cicd-orgrepo }}
    secrets:
       BTP_API_PASSWORD: ${{ secrets.BTP_API_PASSWORD }}
       BTP_TEC_PASSWORD: ${{ secrets.BTP_TEC_PASSWORD }}
       GIT_CICD_TOKEN: ${{ secrets.GIT_CICD_TOKEN }}
       GIT_CICD_APP_PRIVATE_KEY: ${{ secrets.GIT_CICD_APP_PRIVATE_KEY }}
